@host=https://localhost:7005
# change to environment variables

POST {{host}}/auth/change-password
Content-Type: application/json

{    
    "Id": "B722CE14-C14E-4B56-8CE1-4D41D0FB7EF7",
    "NewPassword": "1234"
}