@host=https://localhost:7005

POST {{host}}/auth/signup
Content-Type: application/json

{
    "Name": "Aroldo Lenon Jales dos Santos",    
    "Email": "aroldo@email.com",    
    "Password": "Passwd#FooBar42"
}